package view;
/**
 * @author Gustavo H. Nava
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnNovaVenda = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnCadProduto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnCadClientes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Venda");

        mnNovaVenda.setText("Nova Venda");
        mnNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNovaVendaActionPerformed(evt);
            }
        });
        jMenu1.add(mnNovaVenda);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Produto");

        mnCadProduto.setText("Cadastro");
        mnCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(mnCadProduto);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cliente");

        mnCadClientes.setText("Cadastro");
        mnCadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadClientesActionPerformed(evt);
            }
        });
        jMenu3.add(mnCadClientes);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Relatórios");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNovaVendaActionPerformed
        ViewVenda venda = new ViewVenda();
        venda.setLocationRelativeTo(this);
        venda.setVisible(true);
    }//GEN-LAST:event_mnNovaVendaActionPerformed

    private void mnCadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadClientesActionPerformed
        ViewCadastroCliente cadCliente = new ViewCadastroCliente();
        cadCliente.setLocationRelativeTo(this);
        cadCliente.setVisible(true);
    }//GEN-LAST:event_mnCadClientesActionPerformed

    private void mnCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadProdutoActionPerformed
        ViewCadastroProduto cadProduto = new ViewCadastroProduto();
        cadProduto.setLocationRelativeTo(this);
        cadProduto.setVisible(true);
    }//GEN-LAST:event_mnCadProdutoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnCadClientes;
    private javax.swing.JMenuItem mnCadProduto;
    private javax.swing.JMenuItem mnNovaVenda;
    // End of variables declaration//GEN-END:variables
}
